### ISSUE TITLE
Get all cookies as Object

### ISSUE THREAD

**Issue by LestaD** [pillarjs/cookies#67] opened 2016-02-08 16:01 UTC
Maybe add method `.all()` ?

**Comment by jonathanong** [comment] 2016-02-29 06:09
what's the use-case for this?

**Comment by jonathanong** [comment] 2016-02-29 06:10
dupe of: https://github.com/pillarjs/cookies/issues/52 feel free to add your inputs there!

**Closed by jonathanong** 2016-02-29 06:10 UTC
