### ISSUE TITLE
Set cookies does not return with implicitly returned conditional

### ISSUE THREAD

**Issue by TXredking** [pillarjs/cookies#81] opened 2016-10-12 17:02 UTC
Trying to set a cookie like so...

```
if (req.query.thing === 'true') try {
    res.cookies.set('name', 2431234, {expires: moment().add(1, 'h').toDate()})
} catch(err) {
    console.log(err)
}
```

The above code works as expected but there is no need for the catch so in interest of conciseness I am trying this...

`
if (req.query.thing === 'true') res.cookies.set('name', 2431234, {expires: moment().add(1, 'h').toDate()})
`
^ This does not work. Other cookies I've set are making it through and are set to the header but this one isn't. Also any actions below this statement are not run.

I have traced the function through the npm module and it makes almost 100% of the way just never returns. 

Why would this be the case? Not sure if really an issue per se or something else.

**Comment by dougwilson** [comment] 2016-10-12 17:14
Would it be possible to provide a full file that I can copy and paste and run to see the issue so I can also attach a debugger? Just copying that line into an existing app I have works without issue and sets the cookie, so not sure what is happening, but of course I had to assume that your `req.query` was, how `res.cookies` was populated, and more. To help me out and provide an environment such that we are running the same test, can you provide all the following information?

1. Version of this module you are using.
2. Version of Node.js you are using.
3. Version of `moment` you are using.
4. A full JavaScript file I can copy and paste and run without making any changes to the source code (as in, it must declare all the variables and set up everything). If this ends up including other module, please list the exact version of those as well.
5. Provide instructions for how to run your example code. Perhaps it's just to make a HTTP request to a given URL. Also provide a description of what happens when it doesn't work and what you expect to happen.

Thanks!

**Comment by TXredking** [comment] 2016-10-17 14:50
@dougwilson 

I apologize for the delay. I am working on getting you all the information you need.
I can tell you that I am using...
- Node v6.6.0 
- Cookies v0.5.0
- Moment v2.8.3

**Comment by dougwilson** [comment] 2016-10-20 03:07
Hi @TXredking , I tried again with those versions, and still was not able to reproduce the issue.

**Comment by dougwilson** [comment] 2016-11-13 06:25
Hi @TXredking I'm going to close this issue since I haven't been able to reproduce and didn't hear back on my last response. If you're up to it, please feel free to drop a pull request by that fixes your issue :)

**Closed by dougwilson** 2016-11-13 06:25 UTC
